CIRCUITPY_WIFI_SSID = "YOUR WIFI SSID"
CIRCUITPY_WIFI_PASSWORD = "YOUR WIFI PASSWORD"
ADAFRUIT_AIO_USERNAME = "YOUR ADAFRUIT USERNAME (copy from Adafruit IO Key Section)"
ADAFRUIT_AIO_KEY      = "YOUR ADAFRUIT IO KEY (copy from Adafruit IO Key Section)"
